ROWS = 3 # normally 4
COLUMNS = 8 # normally 8
X_OFFSET = 60
Y_OFFSET = 60
COLLISION_Y_SHIFT = 15

COLOR_EASY = "green"
COLOR_MEDIUM = "yellow"
COLOR_HARD = "red"

SPEED_EASY = 1
SPEED_MEDIUM = 1
SPEED_HARD = 2

LASER_SPEED = -6
LASER_COLOR = "red"
LASER_COOLDOWN_EASY = 2000
LASER_COOLDOWN_MEDIUM = 1500
LASER_COOLDOWN_HARD = 1000

EXTRA_ALIEN_Y_POSITION = 80
EXTRA_ALIEN_SPEED = 3
EXTRA_ALIEN_SPAWN_TIME_MIN = 400
EXTRA_ALIEN_SPAWN_TIME_MAX = 800

ALIEN_POINTS = 100
EXTRA_ALIEN_POINTS = 300